name: Update Profile README

on:
    schedule:
        # Runs every 6 hours (automated updates)
        - cron: '0 */6 * * *'
    workflow_dispatch:
        # Manual trigger - restricted to repository admins only
    # Removed push trigger to prevent unauthorized executions

jobs:
    update-readme:
        runs-on: ubuntu-latest
        name: Update Profile README
        permissions:
            contents: write
            actions: read
            metadata: read

        steps:
            - name: Check if user is admin
              id: check-admin
              run: |
                # Only proceed if triggered by schedule or if user has admin access
                if [[ "${{ github.event_name }}" == "schedule" ]]; then
                  echo "Triggered by schedule, proceeding..."
                  echo "proceed=true" >> $GITHUB_OUTPUT
                elif [[ "${{ github.actor }}" == "${{ github.repository_owner }}" ]]; then
                  echo "Triggered by repository owner, proceeding..."
                  echo "proceed=true" >> $GITHUB_OUTPUT
                else
                  echo "Triggered by non-admin user, skipping..."
                  echo "proceed=false" >> $GITHUB_OUTPUT
                fi

            - name: Checkout
              if: steps.check-admin.outputs.proceed == 'true'
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Update README with latest activity
              if: steps.check-admin.outputs.proceed == 'true'
              uses: jamesgeorge007/github-activity-readme@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  COMMIT_MSG: 'Update profile with latest GitHub activity'
                  MAX_LINES: 5

            - name: Update WakaTime Stats
              if: steps.check-admin.outputs.proceed == 'true'
              uses: anmol098/waka-readme-stats@master
              with:
                  WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SHOW_PROJECTS: 'False'
                  SHOW_PROFILE_VIEWS: 'False'
                  SHOW_DAYS_OF_WEEK: 'True'
                  SHOW_LANGUAGE: 'True'
                  SHOW_OS: 'True'
                  SHOW_TIMEZONE: 'True'
                  SHOW_EDITORS: 'True'
                  SHOW_LANGUAGE_PER_REPO: 'True'
                  SHOW_SHORT_INFO: 'True'
                  SHOW_LOC_CHART: 'False'

            - name: Commit and push if changed
              if: steps.check-admin.outputs.proceed == 'true'
              run: |
                  git config --global user.email "action@github.com"
                  git config --global user.name "GitHub Action"
                  git add -A
                  if ! git diff --cached --quiet; then
                    git commit -m "📊 Auto-update profile stats [skip ci]"
                    git push
                  fi
